// Regenerates skills/rxjs4/references/ from doc/.
//
// Copies the Markdown API docs and guides, stripping per-file boilerplate
// (the "This is RxJS v 4" banner and the "### Location" source/dist file
// listings), and generates references/operator-index.md from the signature
// headings found in the operator docs.
//
// Usage: deno run --allow-read --allow-write skills/build.js

const REPO = new URL('..', import.meta.url).pathname;
const OUT = `${REPO}skills/rxjs4/references`;

const SOURCES = [
  {src: 'doc/api', dest: 'api'},
  {src: 'doc/gettingstarted', dest: 'guides'},
  {src: 'doc/howdoi', dest: 'howdoi'},
];

// Upstream doc headings omit `.prototype.` on a few instance methods
// (cross-checked against the instance-method list in api/core/observable.md).
const KIND_FIX = {
  asObservable: 'instance',
  jortSort: 'instance',
  jortSortUntil: 'instance',
  toPromise: 'instance',
};

const walk = async function* (dir) {
  for await (const entry of Deno.readDir(dir)) {
    const path = `${dir}/${entry.name}`;
    if (entry.isDirectory) yield* walk(path);
    else if (entry.name.endsWith('.md')) yield path;
  }
};

const strip = (text) => {
  const lines = text.split('\n')
    .filter((ln) => !ln.startsWith('# This is RxJS v 4.'));
  const loc = lines.findIndex((ln) => /^#{2,4} Location/.test(ln));
  return (loc === -1 ? lines : lines.slice(0, loc))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim() + '\n';
};

// --- Copy and strip docs ---

await Deno.remove(OUT, {recursive: true}).catch(() => {});

for (const {src, dest} of SOURCES) {
  for await (const path of walk(`${REPO}${src}`)) {
    const rel = path.slice(`${REPO}${src}/`.length);
    const outPath = `${OUT}/${dest}/${rel}`;
    await Deno.mkdir(outPath.replace(/\/[^/]+$/, ''), {recursive: true});
    await Deno.writeTextFile(outPath, strip(await Deno.readTextFile(path)));
  }
}

// --- Build the operator index from signature headings ---

const entries = [];

for await (const path of walk(`${OUT}/api/core/operators`)) {
  const text = await Deno.readTextFile(path);
  const lines = text.split('\n');
  const sigs = lines
    .map((ln) => ln.match(/^#{2,4} `(.+?)`/)?.[1])
    .filter(Boolean);

  // First non-empty line that is not a heading or a source link.
  const desc = lines
    .find((ln) =>
      ln.trim() !== '' && !ln.startsWith('#') && !ln.startsWith('[&#x24C8;')
    ) ?? '';
  const sentence = (desc.match(/^.*?[.!?](?=\s|$)/)?.[0] ?? desc).trim();

  for (const sig of sigs) {
    const m = sig.match(/^Rx\.Observable(\.prototype)?\.([\w$]+)/);
    if (m == null) continue;
    entries.push({
      name: m[2],
      kind: KIND_FIX[m[2]] ?? (m[1] ? 'instance' : 'static'),
      sig,
      sentence,
      file: path.slice(`${OUT}/`.length),
    });
  }
}

entries.sort((a, b) =>
  a.name.localeCompare(b.name) || a.kind.localeCompare(b.kind)
);

const esc = (s) => s.replace(/\|/g, '\\|');
const rows = entries.map((e) =>
  `| \`${e.name}\` | ${e.kind} | \`${esc(e.sig)}\` | ${esc(e.sentence)} ` +
  `| [${e.file.split('/').at(-1)}](${e.file}) |`
);

const index = `# RxJS v4 Operator Index

Every \`Rx.Observable\` static and instance method, extracted from the
signature headings in \`api/core/operators/\`. Aliases (e.g. \`map\`/\`select\`,
\`tap\`/\`do\`, \`flatMap\`/\`selectMany\`) appear as separate rows pointing at the
same doc file. Generated by \`skills/build.js\` — do not edit by hand.

| Method | Kind | Signature | Description | Doc |
|---|---|---|---|---|
${rows.join('\n')}
`;

await Deno.writeTextFile(`${OUT}/operator-index.md`, index);

console.log(`Wrote ${entries.length} index entries.`);
